apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster1
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/giannisalinetti/gitops-lab-apps-dev.git
      revision: main
      directories:
      - path: cluster1-dev/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/giannisalinetti/gitops-lab-apps-dev.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: hello-openshift

